### ISSUE TITLE
Create 3 pre-defined static pages

### ISSUE THREAD

**Issue by George-Cleal** [khmdagal/The-Collective-Foundation#4]
***User Story***

AS AN admin
I WANT TO have access to three, pre-defined static pages embedded as a tab as part [of my main website ](https://starter-kit-slji.onrender.com/)
SO THAT I can use these to publish content for the first version of my website

Acceptance Criteria

GIVEN I am on Collective Foundation website
WHEN I view the admin page
THEN it should display the information of three pages with the same static modules (fetched from database)

**Comment by salehpirouzi-cyf** [comment]
Note that there may be a later backlog issue to allow the admin to create a blank page as part of an existing website. This issue is a one-off task to build the first version of the Website

At this point, the requirement for this task is to have three pages (Home, About, Contact) in the database. Your backend needs to get all available pages from the database when it is called. Your frontend should call the backend and display all pages in the admin page.

**Comment by salehpirouzi-cyf** [comment]
3

**Comment by George-Cleal** [comment]
Blocks: https://github.com/khmdagal/The-Collective-Foundation/issues/13
